#! /bin/sh

set -e

# features
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_EXCEPTION_HANDLING=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_EXTENDED_CONST=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_MULTI_MEMORY=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_TAILCALL=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_THREADS=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASI_THREADS=ON"
#EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASI_LITTLEFS=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_USE_USER_SCHED=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_DYLD=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_DYLD_DLFCN=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_EXCEPTION_HANDLING=ON"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASM_CUSTOM_PAGE_SIZES=ON"

# debug
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug"

# coverage
# EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_COVERAGE=ON"

# fuzzer
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_FUZZER=ON"

TOYWASM_EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS}" \
APP_EXTRA_CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug" \
../build-toywasm-and-app.sh
