#! /bin/sh

set -e

TOPDIR=$(cd $(dirname $0) && pwd -P)/../..

# features
. ${TOPDIR}/all_features.sh

# disable wasi by default
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASI=OFF"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASI_THREADS=OFF"
# prefer the user sched as it's expected more deterministic
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_USE_USER_SCHED=ON"

EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_BUILD_CLI=OFF"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_BUILD_UNITTEST=OFF"
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DBUILD_TESTING=OFF"

# wasi
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_WASI=ON"
APP_EXTRA_CMAKE_OPTIONS="${APP_EXTRA_CMAKE_OPTIONS} -DFUZZ_WASI=ON"

# debug
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug"
APP_EXTRA_CMAKE_OPTIONS="${APP_EXTRA_CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug"

# coverage
# EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_COVERAGE=ON"

# fuzzer
EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS} -DTOYWASM_ENABLE_FUZZER=ON"

TOYWASM_EXTRA_CMAKE_OPTIONS="${EXTRA_CMAKE_OPTIONS}" \
APP_EXTRA_CMAKE_OPTIONS="${APP_EXTRA_CMAKE_OPTIONS}" \
../build-toywasm-and-app.sh
