#undef ECTX
#undef EXECUTING
#undef INSN_FAIL
#undef INSN_FAIL_RESTARTABLE
#undef INSN_IMPL
#undef INSN_SUCCESS
#undef INSN_SUCCESS_BLOCK_END
#undef INSN_SUCCESS_RETURN
#undef LOAD_PC
#undef LOAD_STACK_PTR
#undef ORIG_PC
#undef PREPARE_FOR_POSSIBLE_RESTART
#undef RELOAD_PC
#undef SAVE_PC
#undef SAVE_STACK_PTR
#undef STACK
#undef STACK_ADJ
#undef VALIDATING
#undef VCTX
#undef ep
#undef pop_val
#undef push_val
