/* this file is generated by genvfs.sh */
#include "wasi_vfs_types.h"

struct wasi_vfs_ops {
        int (*fd_fallocate)(struct wasi_fdinfo *fdinfo, uint64_t offset,
                            wasi_off_t len);
        int (*fd_ftruncate)(struct wasi_fdinfo *fdinfo, wasi_off_t size);
        int (*fd_writev)(struct wasi_fdinfo *fdinfo, const struct iovec *iov,
                         int iovcnt, size_t *result);
        int (*fd_pwritev)(struct wasi_fdinfo *fdinfo, const struct iovec *iov,
                          int iovcnt, wasi_off_t off, size_t *result);
        int (*fd_get_flags)(struct wasi_fdinfo *fdinfo, uint16_t *result);
        int (*fd_readv)(struct wasi_fdinfo *fdinfo, const struct iovec *iov,
                        int iovcnt, size_t *result);
        int (*fd_preadv)(struct wasi_fdinfo *fdinfo, const struct iovec *iov,
                         int iovcnt, wasi_off_t off, size_t *result);
        int (*fd_fstat)(struct wasi_fdinfo *fdinfo, struct wasi_filestat *stp);
        int (*fd_lseek)(struct wasi_fdinfo *fdinfo, wasi_off_t offset,
                        int whence, wasi_off_t *result);
        int (*fd_fsync)(struct wasi_fdinfo *fdinfo);
        int (*fd_fdatasync)(struct wasi_fdinfo *fdinfo);
        int (*fd_futimes)(struct wasi_fdinfo *fdinfo,
                          const struct utimes_args *args);
        int (*fd_close)(struct wasi_fdinfo *fdinfo);
        int (*dir_rewind)(struct wasi_fdinfo *fdinfo);
        int (*dir_seek)(struct wasi_fdinfo *fdinfo, uint64_t offset);
        int (*dir_read)(struct wasi_fdinfo *fdinfo, struct wasi_dirent *wde,
                        const uint8_t **namep, bool *eod);
        int (*path_fdinfo_alloc)(struct path_info *pi,
                                 struct wasi_fdinfo **fdinfop);
        int (*path_open)(struct path_info *pi,
                         const struct path_open_params *params,
                         struct wasi_fdinfo *fdinfo);
        int (*path_unlink)(const struct path_info *pi);
        int (*path_mkdir)(const struct path_info *pi);
        int (*path_rmdir)(const struct path_info *pi);
        int (*path_symlink)(const char *target_buf,
                            const struct path_info *pi);
        int (*path_readlink)(const struct path_info *pi, char *buf,
                             size_t buflen, size_t *resultp);
        int (*path_link)(const struct path_info *pi1,
                         const struct path_info *pi2);
        int (*path_rename)(const struct path_info *pi1,
                           const struct path_info *pi2);
        int (*path_stat)(const struct path_info *pi,
                         struct wasi_filestat *stp);
        int (*path_lstat)(const struct path_info *pi,
                          struct wasi_filestat *stp);
        int (*path_utimes)(const struct path_info *pi,
                           const struct utimes_args *args);
        int (*path_lutimes)(const struct path_info *pi,
                            const struct utimes_args *args);
        int (*fs_umount)(struct wasi_vfs *vfs);
};
